// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "remi-ssc",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Remi",
            targets: ["AppModule"],
            bundleIdentifier: "com.prathamsnehi.remi-ssc",
            teamIdentifier: "T296YJXC87",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "We use camera in AR to detect faces of your loved ones. ")
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/SFace.mlmodelc"),
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)