//
//  FaceRecognitionService.swift
//  remi
//
//  Created by Pratham S on 1/19/26.
//

import UIKit
import Vision
import CoreML
import SwiftData
import Accelerate

/// Helper service to identify and register faces using MobileFaceNet
actor FaceRecognitionService {
    static let shared = FaceRecognitionService()
    
    // The model wrapper (loads pre-compiled model from Bundle)
    private var model: MobileFaceNet?
    
    private init() {
        // Initialize the model on first use
        do {
            self.model = try MobileFaceNet()
        } catch {
            print("Failed to load MobileFaceNet: \(error)")
        }
    }
    
    // MARK: - Integration Points
    
    /// Generates an embedding from UIImage (for Normal Registraion Flow)
    /// Inputs:
    /// image: UIImage
    /// faceRect: bounding box generated by vision library
    /// orientation? .right to make face upright
    /// NOTE TO SELF: do NOT perform any transformations on the input image
    func generateEmbedding(from image: UIImage) async -> [Double]? {
        guard let buffer = image.toCVPixelBuffer() else { return nil }
        
        // Auto-detect face in the registration image
        let request = VNDetectFaceRectanglesRequest()
        // Our new toCVPixelBuffer 'bakes' the orientation into the buffer, so it is now Upright (.up)
        let handler = VNImageRequestHandler(cvPixelBuffer: buffer, orientation: .up) 
        
        do {
            try handler.perform([request])
            if let result = request.results?.sorted(by: { $0.boundingBox.width > $1.boundingBox.width }).first {
                 return computeEmbedding(from: buffer, faceRect: result.boundingBox, orientation: .up)
            }
        } catch {
            print("Registration face detection failed: \(error)")
        }
        
        // Fallback if detection fails (though we should probably fail)
        return nil 
    }
    
    /// Generates an embedding from a pixel buffer (for AR flow)
    /// Inputs:
    /// buffer: cvPixelBuffer
    /// faceRect: bounding box generated by vision library
    /// orientation? .right to make face upright
    /// NOTE TO SELF: do NOT perform any transformations on the input pixel buffer
    func generateEmbedding(from buffer: CVPixelBuffer, faceRect: CGRect, orientation: CGImagePropertyOrientation = .right) async -> [Double]? {
        return computeEmbedding(from: buffer, faceRect: faceRect, orientation: orientation)
    }
    
    // MARK: - Internal Logic
    
    /// compute embedding based on given cvPixelBuffer and bouding face rectangle
    /// Inputs:
    /// buffer: the complete raw cvPixelBuffer (uncropped, unrotated)
    /// faceRect: bouding box generated by Vision library
    /// orientation?: .right to make face upright
    private func computeEmbedding(from buffer: CVPixelBuffer, faceRect: CGRect, orientation: CGImagePropertyOrientation = .right) -> [Double]? {
        guard let model = model else { return nil }
        
        // 1. detect and crop face, resize to 112x112:
        guard let croppedFace = buffer.resizeForMobileFaceNet(normRect: faceRect) else { return nil }
        
        // 2. Run Inference
        do {
            // MobileFaceNetInput init requires 'input_1'
            let input = MobileFaceNetInput(input_1: croppedFace)
            let output = try model.prediction(input: input)
            
            // 3. Extract Vector from 'var_950'
            let multiArray = output.var_950
            return multiArray.toDoubleArray()
            
        } catch {
            print("Inference error: \(error)")
            return nil
        }
    }
    
    /// Finds the best match for an embedding among candidates
    /// Returns (bestMatchId, confidence)
    func findBestMatch(for embedding: [Double], candidates: [(PersistentIdentifier, [Double])]) -> (PersistentIdentifier, Double)? {
        var bestMatchID: PersistentIdentifier?
        var minDistance: Double = 1.0
        let strictThreshold = 0.6
        
        for (id, knownVector) in candidates {
            guard !knownVector.isEmpty else { continue }
            
            var distance = getFaceDistance(embedding, knownVector)
            print("🔍 Match Candidate: \(distance)") // Debug log
            if distance < strictThreshold {
                if distance < minDistance {
                    minDistance = distance
                    bestMatchID = id
                }
            }
        }
        
        if let id = bestMatchID {
            return (id, (1.0 - minDistance))
        }
        
        return nil
    }
}
