//
//  FaceRecognitionService.swift
//  remi
//
//  Created by Pratham S on 1/19/26.
//

import UIKit
import Vision
import CoreML
import SwiftData
import Accelerate

/// Helper service to identify and register faces using MobileFaceNet
actor FaceRecognitionService {
    static let shared = FaceRecognitionService()
    
    // The model wrapper (loads pre-compiled model from Bundle)
    private var model: MobileFaceNet?
    
    private init() {
        // Initialize the model on first use
        do {
            self.model = try MobileFaceNet()
        } catch {
            print("Failed to load MobileFaceNet: \(error)")
        }
    }
    
    // MARK: - Integration Points
    
    /// Generates an embedding from UIImage (for Normal Registraion Flow)
    /// Inputs:
    /// image: UIImage
    /// NOTE TO SELF: do NOT perform any transformations on the input image
    func generateEmbedding(from image: UIImage) async -> [Double]? {
        // system orientation: upright -> no orientation transformations needed (.up)
        guard let buffer = image.toCVPixelBuffer() else { return nil }
        
        let request = VNDetectFaceRectanglesRequest()
        let handler = VNImageRequestHandler(cvPixelBuffer: buffer, orientation: .up)
        
        do {
            try handler.perform([request])
            
            if let result = request.results?.sorted(by: { $0.boundingBox.width > $1.boundingBox.width }).first {
                
                // 2. Use Extension with .up orientation
                guard let croppedFaceBuffer = buffer.resizeForMobileFaceNet(normRect: result.boundingBox, orientation: .up) else {
                    return nil
                }
                
                // 3. Run Inference
                return computeEmbedding(from: croppedFaceBuffer)
            }
        } catch {
            print("Registration face detection failed: \(error)")
        }
        return nil
    }
    
    /// Generates an embedding from a pixel buffer (for AR flow)
    /// Inputs:
    /// buffer: cvPixelBuffer
    /// faceRect: bounding box generated by vision library
    /// orientation? .right to make face upright
    /// NOTE TO SELF: do NOT perform any transformations on the input pixel buffer
    func generateEmbedding(from buffer: CVPixelBuffer, faceRect: CGRect) async -> [Double]? {
        // we request faceRect here because the code in ARViewContainer already does that for us
        // so don't want to do this thing twice
        
        guard let croppedFaceBuffer = buffer.resizeForMobileFaceNet(normRect: faceRect, orientation: .right) else { return nil }
        
        do {
            return computeEmbedding(from: croppedFaceBuffer)
        }
    }
    
    func generateEmbedding(from wrapper: PixelBufferWrapper, faceRect: CGRect) async -> [Double]? {
            return await generateEmbedding(from: wrapper.buffer, faceRect: faceRect)
        }
    
    
    
    // MARK: - Internal Logic
    
    /// compute face fingerpting based on an input pixel buffer as-is (no transformations made)
    /// this is because we assume all transformations are already made, and this is the final destination
    private func computeEmbedding(from buffer: CVPixelBuffer) -> [Double]? {
        guard let model = model else { return nil }
        
        // 2. Run Inference
        do {
            // MobileFaceNetInput init requires 'input_1'
            let input = MobileFaceNetInput(input_1: buffer)
            let output = try model.prediction(input: input)
            
            // 3. Extract Vector from 'var_950'
            let multiArray = output.var_950
            let rawVector = multiArray.toDoubleArray()
            return normalize(rawVector) // normalized vector, as REQUIRED by MobileFaceNet model
            
        } catch {
            print("Inference error: \(error)")
            return nil
        }
    }
    
    /// Finds the best match for an embedding among candidates
    /// Returns (bestMatchId, confidence)
    func findBestMatch(for embedding: [Double], candidates: [(PersistentIdentifier, [Double])]) -> (PersistentIdentifier, Double)? {
        var bestMatchID: PersistentIdentifier?
        var minDistance: Double = Double.greatestFiniteMagnitude
        let matchThreshold = 0.80
        
        for (id, knownVector) in candidates {
            guard knownVector.count == embedding.count else {
                print("Vector dimension mismatch")
                continue
            }
            guard !knownVector.isEmpty else {
                print("No known vectors")
                continue
            }
            
            var distance = getFaceDistance(embedding, knownVector)
            print("🔍 Match Candidate: \(distance)") // Debug log
            
            if distance < matchThreshold {
                if distance < minDistance {
                    minDistance = distance
                    bestMatchID = id
                }
            }
        }
        
        if let id = bestMatchID {
            let confidence = max(0.0, 1.0 - minDistance)
            return (id, confidence)
        }
        
        return nil
    }
}

private func normalize(_ vector: [Double]) -> [Double] {
    var result = vector
    var sum: Double = 0
    // Calculate sum of squares
    vDSP_svesqD(vector, 1, &sum, vDSP_Length(vector.count))
    let magnitude = sqrt(sum)
    
    // Divide every element by magnitude to get unit vector
    if magnitude > 0 {
        var scale = 1.0 / magnitude
        vDSP_vsmulD(vector, 1, &scale, &result, 1, vDSP_Length(vector.count))
    }
    return result
}
